# Generated by Django 5.1.6 on 2025-03-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_country_dis_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dis',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.country'),
            preserve_default=False,
        ),
    ]
